In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\ACER\Desktop\Projects\Finance\Data\fraud_data.csv')

df.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_ID,Transaction_Date,...,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,Is_Fraud,Transaction_Currency,Customer_Contact,Transaction_Description,Customer_Email
0,d5f6ec07-d69e-4f47-b9b4-7c58ff17c19e,Osha Tella,Male,60,Kerala,Thiruvananthapuram,Thiruvananthapuram Branch,Savings,4fa3208f-9e23-42dc-b330-844829d0c12c,23-01-2025,...,Restaurant,74557.27,Voice Assistant,"Thiruvananthapuram, Kerala",POS,0,INR,+9198579XXXXXX,Bitcoin transaction,oshaXXXXX@XXXXX.com
1,7c14ad51-781a-4db9-b7bd-67439c175262,Hredhaan Khosla,Female,51,Maharashtra,Nashik,Nashik Branch,Business,c9de0c06-2c4c-40a9-97ed-3c7b8f97c79c,11-01-2025,...,Restaurant,74622.66,POS Mobile Device,"Nashik, Maharashtra",Desktop,0,INR,+9191074XXXXXX,Grocery delivery,hredhaanXXXX@XXXXXX.com
2,3a73a0e5-d4da-45aa-85f3-528413900a35,Ekani Nazareth,Male,20,Bihar,Bhagalpur,Bhagalpur Branch,Savings,e41c55f9-c016-4ff3-872b-cae72467c75c,25-01-2025,...,Groceries,66817.99,ATM,"Bhagalpur, Bihar",Desktop,0,INR,+9197745XXXXXX,Mutual fund investment,ekaniXXX@XXXXXX.com
3,7902f4ef-9050-4a79-857d-9c2ea3181940,Yamini Ramachandran,Female,57,Tamil Nadu,Chennai,Chennai Branch,Business,7f7ee11b-ff2c-45a3-802a-49bc47c02ecb,19-01-2025,...,Entertainment,58177.08,POS Mobile App,"Chennai, Tamil Nadu",Mobile,0,INR,+9195889XXXXXX,Food delivery,yaminiXXXXX@XXXXXXX.com
4,3a4bba70-d9a9-4c5f-8b92-1735fd8c19e9,Kritika Rege,Female,43,Punjab,Amritsar,Amritsar Branch,Savings,f8e6ac6f-81a1-4985-bf12-f60967d852ef,30-01-2025,...,Entertainment,16108.56,Virtual Card,"Amritsar, Punjab",Mobile,0,INR,+9195316XXXXXX,Debt repayment,kritikaXXXX@XXXXXX.com

In [4]:
fruad_data = df[df['Is_Fraud'] == 1]

In [5]:
fruad_data.head()

,Customer_ID,Customer_Name,Gender,Age,State,City,Bank_Branch,Account_Type,Transaction_ID,Transaction_Date,...,Merchant_Category,Account_Balance,Transaction_Device,Transaction_Location,Device_Type,Is_Fraud,Transaction_Currency,Customer_Contact,Transaction_Description,Customer_Email
17,99d95f63-a2fa-4707-b577-f4a008e6700e,Theodore Suri,Male,56,Dadra and Nagar Haveli and Daman and Diu,Silvassa,Silvassa Branch,Business,aa3832eb-c0f0-48b1-b195-a376a1e17797,24-01-2025,...,Restaurant,74322.85,Biometric Scanner,"Silvassa, Dadra and Nagar Haveli and Daman and...",Desktop,1,INR,+9194951XXXXXX,Gift for colleague,theodoreXXX@XXXXX.com
29,54fb2e67-b087-4522-a5c4-af69f95cd9df,Jalsa Menon,Male,24,Chhattisgarh,Durg,Durg Branch,Savings,b33c79ab-4d81-4d12-baf3-2b13cf67608a,28-01-2025,...,Electronics,60905.65,ATM Booth Kiosk,"Durg, Chhattisgarh",POS,1,INR,+9195352XXXXXX,Mobile phone payment,jalsaXXX@XXXXXXX.com
32,ad5f8799-179f-4b1d-887c-cace22837d3e,Ishanvi Kant,Female,39,Uttar Pradesh,Varanasi,Varanasi Branch,Business,0d970d8f-dd99-401b-a7ba-83a276a7cf49,19-01-2025,...,Groceries,88389.09,QR Code Scanner,"Varanasi, Uttar Pradesh",Mobile,1,INR,+9199750XXXXXX,Property tax payment,ishanviXXXXX@XXXXX.com
54,6e9eaae0-ed2c-40b7-af0c-14e02647a39c,Peter Dhawan,Female,52,Manipur,Imphal,Imphal Branch,Checking,402d686c-e7b1-4857-b8b0-b6c384b56611,10-01-2025,...,Restaurant,56382.68,Wearable Device,"Imphal, Manipur",POS,1,INR,+9191682XXXXXX,Grocery delivery,peterXXXXX@XXXXXX.com
76,f7d6bcdb-2c7e-4456-9cbc-1516a9186b55,Gopal Ratta,Male,28,Haryana,Gurugram,Gurugram Branch,Savings,f2f00aa5-0896-4cc1-bb52-0f7822b1e741,23-01-2025,...,Groceries,75460.68,ATM,"Gurugram, Haryana",Mobile,1,INR,+9198024XXXXXX,Bank transfer,gopalXXXX@XXXXXXX.com

In [6]:
fruad_data.shape

(10088, 24)

In [7]:
fruad_data.to_csv('fraud_data.csv', index=False)